name: Daily Software Updates

on:
  schedule:
    - cron: "0 9 * * *"   # every day at 9:00 AM UTC
  workflow_dispatch:      # allow manual trigger from GitHub UI

jobs:
  run-daily-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run workflow
        run: npm start
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
          MY_PHONE: ${{ secrets.MY_PHONE }}
